### ISSUE TITLE
Clean up naming of transform scripts

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#104]
# Problem
There are a number of scripts used to transform and prepare each state's voter file. As we add more states their naming convention will break down and become cumbersome.

# Solution
Come up with a new naming convention and refactor the files to match. 

# Tasks
1. Propose new naming convention
2. Refactor the files and scripts
3. Insure the testing script completes successfully

**Comment by schuyler1d** [comment]
cool.  I'll take this -- you can assign to me.

**Comment by schuyler1d** [comment]
goals:
* homogenize states names in contacts to 2-letter postal code
* organize _prepare.py files to be abstracted class
* separate csv writer to a class that consumes the transformers (that way a separate consumer can go straight to db, e.g..)
* have a base least-common-denominator validator that is used across all transforms, but the base transformers should also be as strict as possible.
* if things go well we can create a setup.py file and start organizing code more like a library (edited)
