### ISSUE TITLE
Create Vermont transformer

### ISSUE THREAD

**Issue by pjsier** [national-voter-file/national-voter-file#123]
@tanyaschlusser added the Vermont voter file to the Dropbox a few weeks ago, wanted to put an issue here in case someone is interested. Not sure what the current checklist is for creating a transformer in the new setup from scratch, so feel free to edit this with the details

**Comment by slavingia** [comment]
Pretty good README: https://github.com/national-voter-file/national-voter-file/blob/transform1.1/src/python/national_voter_file/transformers/README.md

(best we got at least :))

**Comment by slavingia** [comment]
here's a PR that is setting up a new transformer from scratch: https://github.com/national-voter-file/national-voter-file/pull/158

**Comment by nealchandra** [comment]
FYI for those watching this -- hoping to have a PR for this in the next few days. Good call mentioning it here cause I was worried someone else might pick up the task thinking no one was working on it :P
