### ISSUE TITLE
Global string for missing (genders, party)

### ISSUE THREAD

**Issue by slavingia** [national-voter-file/national-voter-file#151]
"U" (or python object None) is a magic string that is copy/pasted a bunch. Use a global variable or another solution to remove this hack.

Pick a standard (chat with ben and folks in Slack first!) and implement this, and write specs.

- [x] gender
- [x] party

**Comment by JakeStevens** [comment]
The NC transformer marks places where this standard needs to be implemented with #TODO comments. This would be a good place to start looking for magic strings to fix.

**Comment by slavingia** [comment]
going with None, as we now support that
