### ISSUE TITLE
Create Utah Transformer

### ISSUE THREAD

**Issue by slavingia** [national-voter-file/national-voter-file#165]
# Problem

We don't have a Utah transformer yet! Send @slavingia a note to get added to the Dropbox for access to the voter file you'll need to do this.

## References

How to add a new state transformer: https://github.com/national-voter-file/national-voter-file/blob/master/src/python/national_voter_file/transformers/README.md
Example PR for Delaware: https://github.com/national-voter-file/national-voter-file/pull/158

**Comment by alexdej** [comment]
Started working on this one.
