### ISSUE TITLE
Handling a single at-large district.

### ISSUE THREAD

**Issue by slavingia** [national-voter-file/national-voter-file#166]
# Problem

States with just one at-large district should be handled specially.

## References

Comment by Neal:

> So the next question is how should we handle the CONGRESSIONAL_DIST field for states with only a single district? My understanding is that it would be incorrect to refer to them as the 1st district since they are distinct from that. I was going to just go with AL for the VT transformer, but I don't know if we already have a standard approach for this/if it's OK for this field to be a string.

Comments on: #158

**Comment by BenGalewsky** [comment]
The reference for this would be whatever we put in the jurisdiction table (as pulled down from U.S. census) -  take a look at src/python/national_voter_file/census_reporter for details on how to run this for VT

**Comment by slavingia** [comment]
Ah yes. @squidarth maybe worth looking into that?

**Comment by squidarth** [comment]
@slavingia @BenGalewsky I can look into this.

@BenGalewsky Are you saying that we should use the names for these districts given in the census? For  DE, the census just says "Congressional District 1" unless I'm reading this wrong.

**Comment by BenGalewsky** [comment]
So I went ahead and ran our script that downloads census data for various jursidictions at:
`python3.5 national_voter_file/censusreporter/getCensus.py -s VT -t Congress`

It generates a single record for FIPS: 50000US5000

It calls the district 1

That is certainly what we should put in the congressional district column in the output of the transform. That way when we load the records in, they will get associated with that FIPS and all of it's socio-economic data. 

Are you saying that the human readable title of that jurisdiction shouldn't be `Congressional District 1`? We can change the dimension to title it correctly and then we are done.
