### ISSUE TITLE
Create Python Geocode Crawler

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#17]
We can geocode up to 60,000 addresses per day with mapzen. Create a python demon to look for households that need geocoding and call the api while respecting data .throttles
1. Add lat/long and geocode status to household dim
2. Set status to "pending" for all records
3. Create python script to query all households where status is pending and call mapzen api
4. See if we can find a good match in the results.
   4a. If yes - update the lat/long in the record and change status to "mapzen"
   4b. If no - set status to failed mapzen

**Comment by rileytaylor** [comment]
https://gist.github.com/dannguyen/036a62e32fc9f6765b82 example of a python geocoder for starbucks locations using mapzen

**Comment by easherma** [comment]
FYI but mainly a tangent: Mapzen [has a simple bulk geocoding app written in node](https://github.com/pelias/scripts-batch-search): 

I can help with this, but need to know what the structure is of the data itself that we'll be querying for. It sounds like this is all living in a postgres database? 

I do have a bulk geocoder I've been working on. It might be headed in a direction that's overkill and the code is definitely rough and in early stages; it uses luigi as a framework for managing the data pipeline:

https://github.com/easherma/cbackend/blob/master/tasks.py

**Comment by BenGalewsky** [comment]
Eric -- I emailed you a CSV with a dump of households (no names or PII) from our database. Hope that clarifies it

**Comment by bradleygolden** [comment]
I've forked the repo and am working on it on this branch: https://github.com/bradleygolden/national-voter-file/tree/geocoding

**Comment by slavingia** [comment]
@bradleygolden how is this going? I have a friend that may be interested in tackling this depending on how far you are with it.

**Comment by bradleygolden** [comment]
@slavingia feel free to take it! I'm not all that far along.

**Comment by slavingia** [comment]
summoning @howespt

**Comment by BenGalewsky** [comment]
How to add lat/long to household dim
Here's the reference. http://postgis.net/docs/manual-2.1/using_postgis_dbmanagement.html#PostGIS_Geography
Looks like the type is:  GEOGRAPHY(POINT, 4236) 
The 4236 is the SRID number, a unique identifier that specifies what the numbers in the coordinate system mean. SRID 4236 identifies the WGS84 standard (https://en.wikipedia.org/wiki/World_Geodetic_System#WGS84 -- so, like, where exactly is 0,0 on earth?)

**Comment by tanyaschlusser** [comment]
i'd like to take a crack! the geocode status and geolocation will be added to the household_dim separately and the eventual commit will just be the daemon pulling from and pushing to the database
