### ISSUE TITLE
Update transformer template to use new col_map

### ISSUE THREAD

**Issue by slavingia** [national-voter-file/national-voter-file#174]
# Problem

People aren't benefitting from the new col_map as they might miss it.

I'm also a fan of potentially nixing it and asking folks to copy an existing transformer, and just getting all the ones we already have up to date.

(For CO, I found a transformer that was closest in content and columns to mine, and used that.)

**Comment by pjsier** [comment]
I haven't used the transformer template either (also just copied a similar state) so unless anyone has been finding it helpful think we could get rid of it.
