### ISSUE TITLE
Spinning up test database

### ISSUE THREAD

**Issue by slavingia** [national-voter-file/national-voter-file#198]
# Problem

For API developers, we should make it super easy to spin up a docker of Postgres with all-working data.

## Notes

Local is the way to go vs. hosted somewhere

**Comment by BenGalewsky** [comment]
We have some nice test data in data/test/oh.csv

Create a script that will call the loader.py on this from the docker etl container to load up a test database for ETL developers

**Comment by pjsier** [comment]
@BenGalewsky I think we have the instructions for that in the loader README here https://github.com/national-voter-file/national-voter-file/tree/master/load
