### ISSUE TITLE
Active?

### ISSUE THREAD

**Issue by Lvl4Sword** [national-voter-file/national-voter-file#231]
I don't have a problem, just a single question. Is this project still active?

**Comment by joshsmith** [comment]
Hey @Lvl4Sword there are some folks continuing to work on the project but we've kind of stalled at the level of the API. We'd like to get things moving again but need a stronger hand on the project right now. I've personally been swamped with other things.

**Comment by Lvl4Sword** [comment]
What do you need help with? I've been doing a partially related separate project ( https://sking.io/voter ) and this is something I'm incredibly interested in. Willing to help where I can :+1:

**Comment by joshsmith** [comment]
I think there are a number of issues here that not much progress had been made on: https://github.com/national-voter-file/national-voter-file-api/issues

I'd spiked out some initial code but not much done since then.

**Comment by BenGalewsky** [comment]
Actually, @Lvl4Sword the codebase as it stands is still quite useful. We have parsers for several states' voter files and a great framework for building support for new ones. The scripts deploy the data into a high performance data warehouse for pretty deep analysis.

Looking at your site, it looks like the API is not something you would be interested in, right?

Thanks for checking in.

**Comment by joshsmith** [comment]
Yes I should have been more explicit about that.

I’m going to close this since I think the question is answered, and you can always reach out to us personally if you’d like help getting involved.
