### ISSUE TITLE
Populate State Dimension

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#5]

**Comment by BenGalewsky** [comment]
Update the state dimension to include:

* Version #
* Valid from/to
* Population
* Abbreviation
* Full Name
* Datafile cost
* Link to secretary of state website (look at voter file sources spreadsheet for this data)

Create a PDI transform to load this data and maybe a static CSV file or find an online source to consume.

Load the data into the table.

**Comment by JoeNVF** [comment]
Building the new table now, including what is up here as well as census data (same as what counties use).

I don't believe the US Census changes the state FIPS codes, so we can do a static csv to hold the name, abbr, datafile cost, and link to the website.  Then pull census data, merge and load.

Do we want to change other tables like county to no longer store state name and/or abbr, and just point to FIPS (so names can be looked up at query), or keep storing them?

**Comment by JoeNVF** [comment]
This has changed slightly.  State will be added to the jurisdiction_dim and include all the same information has county/congress/etc (already completed).  Once I complete the jurisdiction ETL process that information will be available.

The other information will be put into the reporter_dim.
