### ISSUE TITLE
Document the standard output file produced by python prepare scripts

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#54]
Part of the process for loading states' files into the warehouse is to run them through a python script that is specific to that state. The script cleans up idiosyncratic data and normalizes the file to stage them for ingesting into the warehouse.

The standardized file columns can be found in PrepareUtils.py in src/main/python.

We need to document the meaning of each field in this output file to make it clearer how to write new prepare scripts.

I set up a google spreadsheet to maintain this data. You  can request an editiable link via slack.

One of the biggest things the script do is bust apart monolithic address strings into the [Federal Geographic Data Committee](http://www.urisa.org/clientuploads/directory/GMI/Professional%20Practice/Address%20Standard/AddressStandard_Approved_Apr11_02Content.pdf) standard for addresses using a python module called [usaddress](https://usaddress.readthedocs.io/en/latest/)

Once we have this spec defied we need to go back and insure the Ohio, New York, and Florida loaders produce conformant output and then create a standard loader that will work with all such prepared files.

**Comment by JoeNVF** [comment]
I'll take a loot at this while I'm working on the NC voter information.

If someone else wants to tackle this issue, feel free to take it.

**Comment by tanyaschlusser** [comment]
yay me too! lots of people can help I think :-)

**Comment by slavingia** [comment]
added a bunch, mainly for mailing address.
