### ISSUE TITLE
Create "Hello World" API

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#59]
We need an API to securely vend voter file data.

Help us get started with a simple Elixir application. Even this basic app needs to use API keys.

**Comment by JoshSmith** [comment]
We've decided to go with Elixir / Phoenix here for a few reasons:

- Long-term cost reduction on servers – really critical for a small team with little funding trying to do massive GOTV efforts at election time (2 million simultaneous channels on a single server! Say what!?)
- Bright future of micro-services due to Phoenix presence, the BEAM, OTP generally
- General community excitement and gravitation
- Some rather esoteric architectural musings around Conway's law

You can read some more detailed thoughts about this I wrote up here: https://blog.codecorps.org/moving-to-elixir-and-phoenix/

**Comment by JoshSmith** [comment]
If you'd like to get started, here are some resources:

- Elixir: http://elixir-lang.org/
- Phoenix: http://www.phoenixframework.org/
- _Programming Elixir_: https://pragprog.com/book/elixir/programming-elixir
- _Programming Phoenix_: https://pragprog.com/book/phoenix/programming-phoenix

**Comment by slavingia** [comment]
What would this app do? A quick story/wireframe or whatnot would be useful for me. I can probably tackle this.

**Comment by JoshSmith** [comment]
@slavingia I believe the idea here is to at least let people start hitting the existing voter file data via some basic endpoints.

We should discuss the design here and how minimal this can be. @BenGalewsky thinks it's a good motivational thing. I understand the desire, but I'm not super convinced we have done all the work we need to on use cases. 👈 I am actively working on collecting stories from other orgs, but this takes some time, especially with the bigger players.

**Comment by slavingia** [comment]
got it. yea, there'll be quite a little bit of work involved in getting even an MVP set up.

we could have a "pretend" api that people can hit potentially (test data), just so people have a sense of what will be achievable in the future.

but real data itself, as you mentioned, is gonna be a lot of work :)

**Comment by BenGalewsky** [comment]
We've been collecting user stories in a google spread sheet - I'll send you the link in slack

**Comment by sandramchung** [comment]
Stashed user stories doc here for relevance/safekeeping https://docs.google.com/spreadsheets/d/1m8CgNbfMX5JifzzzFEtY7R2Hf4ufHDeD0LCYAh34kTY/edit#gid=0  I may be able to work on this in the near future.

**Comment by JoeNVF** [comment]
We definitely need to consider security here, types of access, authentication method, encryption (for initial testing we can go simple with self-signed SSL), etc.  This part is key to keeping within the lines for the various user/access rights we need to comply with for the voter files.

This article talks about setting up a basic authentication method, and links to two open source solutions we could utilize:  http://nithinbekal.com/posts/phoenix-authentication/

What method we use will be greatly determined on how we want users to access the information.

**Comment by JoshSmith** [comment]
I highly suggest we use the same auth approach taken in https://github.com/code-corps/code-corps-api

**Comment by JoeNVF** [comment]
I'll take a look in more detail and maybe speak with them about their
implementation.

**Comment by JoshSmith** [comment]
@JoeNVF "them" is me and @begedin 😄

**Comment by JoeNVF** [comment]
Well, that does make it easier.  I took a REALLY quick glance and one thing
stood out to me.  You have a return value of "not email on record" or
something similar.  Are you returning that for just invalid user, or also
for invalid password?

**Comment by JoshSmith** [comment]
@JoeNVF no, we're returning no email for an invalid email, and invalid password when the password is invalid.

**Comment by JoeNVF** [comment]
I'd suggest making it a single message then, it's a security no-no to
return those two separately as it allows attackers to fish for valid
usernames.  That's why you see most major sites returning "Invalid username
and/or password".

**Comment by JoshSmith** [comment]
It's not a security no-no. It's a usability problem. If you want to improve security then force longer passwords (we do), recommend changes to password length and complexity on account registration (we do), rate limit login attempts (we'd like to), enable 2FA (we'd like to), or some other combination of security practices that don't come at the expense of the user's experience.

**Comment by JoshSmith** [comment]
Keep in mind that the _vast majority_ of people who will be authenticating here will be consumers of data and not guardians of the data. The likelihood of a brute force or dictionary attack is severely constrained (if not altogether removed) if you place a 2FA requirement onto accounts that are supposed to be guardians of the data.

**Comment by JoeNVF** [comment]
It's very much a security no-no, here's the OWASP talking about testing for
it.
https://www.owasp.org/index.php/Testing_for_User_Enumeration_and_Guessable_User_Account_(OWASP-AT-002)
.

Yes, it is a minor annoyance to the user, but one they are quite familiar
with given that it is a standard security practice.  It is a simple method
to prevent farming user names to your service.  Everything else you
mentioned is good and should be done, but security is about layering and
you're missing an outer layer.  Doesn't matter if the account is read-only
or full admin, access to any account is the first step to gaining access to
everything.  I've watched the NSA red team take a read-only account and
turn it into full enterprise EA in a matter of minutes (those guys are
good...).

This is a minor change, that implements a system that users are already
familiar with, and prevents one avenue of attack.

As I'm sure you've guessed, security is my specialty, and I'd be happy to
talk about it all day.

**Comment by JoshSmith** [comment]
Probably the better thing I should have said is that this is not even fundamental to the authentication system I described – we're solely pattern matching. If we don't like that we can remove the pattern match in this API implementation and I won't be terribly broken up about it.

**Comment by JoshSmith** [comment]
I would point out, though, that security is not a monolith and the most secure thing to do is not necessarily always the right course of action for you and your users. Were it the most important thing always then we'd have totally air-gapped machines with no networking capability whatsoever. But definitely making a mountain out of a molehill here and my earlier comment that I'm blasé either way for this particular component stands.

**Comment by slavingia** [comment]
IMO we should stick to Flask to keep everything on Python and keep the hurdle low for getting engineers on board to contribute. Heard this feedback a few times when trying to recruit (great) engineers in SF to work on this. The less intimidating the better :)

**Comment by slavingia** [comment]
Changing the title to API just so in the meantime, we don't scare anyone off when they're browsing the Issues page :)

**Comment by slavingia** [comment]
Moving to new `national-voter-file-api` repo.
