### ISSUE TITLE
Convert "prepare" files to "transformer" files

### ISSUE THREAD

**Issue by georgeberry** [national-voter-file/national-voter-file#71]
New transformer format for converting raw data to a standardized format is ready. There may be some bugs which we can work out as we create additional conversion files.

Transformer code here: https://github.com/getmovement/national-voter-file/tree/master/src/main/python/transformers

**Comment by mbiokyle29** [comment]
These look pretty sweet. I have some tests set up for the old prepare script but not much, might make sense to move them over to unittest/integration tests for the transformers?

**Comment by BenGalewsky** [comment]
Yes, @mbiokyle29 ! Please take a look at how to implement unit tests in the new transformers. Work going on right now in the datamodel1.1 branch.
