### ISSUE TITLE
Add validation for missing fields to transformer

### ISSUE THREAD

**Issue by BenGalewsky** [national-voter-file/national-voter-file#79]
The transformers have a capability for identifying fields that have constrained values (gender, party). We need the same checks for empty fields.

I noticed that some rows in Ohio were missing the mailing address country. We should default this to USA. The transform script needs to have a list of fields that cannot be blank and report an error if a transform subclass ever passes a blank value in those fields.

**Comment by pjsier** [comment]
Are the rows null or empty strings? I think the transformer is checking type, but empty strings are passing because they're still strings. Maybe we could include a method that converts all empty strings to `None` so that they fail the type check?
